### PR TITLE
Fixes #10: Views for Image and File versions don't work.

### LINKED ISSUE #10: Views for Image and File versions don't work
The views to display versions of images and files don't work for dexterity and also don't seem to work for archetypes either.

DX
```
http://localhost:8080/Plone/some_image.jpg/versions_history_form?version_id=1#version_preview
```
is trying to get an image from 
```
http://localhost:8080/Plone/some_image.jpg/versions_history_form/++widget++form.widgets.image/@@download/NameOfTheActualImage.jpg
```
Right now this falls back to the versions_history_form without showing an error or image.

In the end it would be nice to be able to download a certain version again and display versions of an image side by side in the comparison view.

### PR DESCRIPTION
**Pull request by rafaelbco**
Fixes #10

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/495/

**Comment by rafaelbco** [comment]
It seems to me this link is about a pull request on plone.app.layout


Rafael Oliveira

**Comment by rafaelbco** [comment]
What do I have to do to get this merged? @jensens

**Comment by jensens** [comment]
Tests need to pass, above link run the coredev buildout with your branch. It looks like there is some side effect in plone.app.widgets see http://jenkins.plone.org/job/pull-request-5.0/495/testReport/junit/plone.app.widgets.tests.test_robot/RobotTestCase/Querystring_Widget_rows_appear_and_disappear_correctly/

You can run tests yourself by logging in with your github account into jenskins.plone.org, got to plone.org/job/pull-request-5.0/build and paste the url of this PR into the textarea. Paste the url of the runner (appears in left column in jenkins) into here and watch.

**Comment by pysailor** [comment]
superseded by #20

**Pull request closed without merging**
