### PR TITLE
Fix test for changed label in `Products.CMFEditions`

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
aha ... seems that we have to split up versions here. The change in Products.CMFEditions Plone 6 only

/cc @mauritsvanrees @jensens

**Comment by jensens** [comment]
Yay, a tests that depends on a text from a different package. Sigh.

**Comment by jensens** [comment]
No further fighting in those cases. Drop Plone 5 support on master. Branch away and new major version.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
ah, thanks @mauritsvanrees ... I also updated buildout.coredev `5.1` and `5.1` because both pointed to this master branch ... maybe you want to update those `sources.cfg` also

**Comment by mauritsvanrees** [comment]
Coredev 5.0 and 5.1 are abandoned. I never update them. You can ignore them.

**Pull request merged**
