### PR TITLE
Initial version for versionable objects is properly created

### LINKED ISSUE #47: Create initial version after adding
The code from `create_initial_version_after_adding` is never executed because of this commit c0d7401 the that changed the handler registered for IObjectAddedEvent to `create_version_on_save`

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #47

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by rafaelbco** [comment]
I think a new test is needed in order to prevent the reintroduction of the bug in the future.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
