### PR TITLE
Change to use filecmp.cmp(shallow=False) instead comparing blobs line by line

### PR DESCRIPTION
**Pull request by datakurre**

### CODE REVIEW

**Comment by datakurre** [comment]
@jenkins-plone-org please run jobs

**Comment by datakurre** [comment]
@jensens Did you manage to try this with RelStorage with blobs in RelStorage?

**Comment by jensens** [comment]
I did not, I do not think it is needed.

With RelStorage 1.x and 2.x usually a shared blobstorage is used. Storing blobs inside the DB is possible, but performance wise not recommended, except Oracle with some rare installations out - and even there a customers Oracle admin decided to not store them inside. This all is not different from ZEO with shared blobs.

For RelStorage 3 (Zope4/Python3) the blob support inside the DB itself was much improved and is the recommended way to store blobs in the DB. It then will create a zope-client cache of files and even if ``os.stat()`` has a different signature ``filecmp.cmp(...)``[1] it will then compare them - and I hope in a more efficient way than we did. 

[1][ the Python documentation says](https://docs.python.org/3/library/filecmp.html#filecmp.cmp):

> If shallow is true, files with identical os.stat() signatures are taken to be equal. Otherwise, the contents of the files are compared.

**Comment by datakurre** [comment]
@jensens Ok. I will then add a changelog note. @fredvd raised valid concerns that I am cutting corners here by comparing blobs directly on filesystem. I did try out shared blobs and non-shared blobs with ZODB blob storage and for those this worked. If you believe that this Ok also for RelStorage users, it is good enough for me.

**Comment by datakurre** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
